In [ ]:
#This is Box of tricks useful for TF

In [11]:
import numpy as np

x = np.arange(1,3+1,1) # Return evenly spaced values within a given interval.

scores = np.array([1.0, 2.0, 3.0])
print (scores*10)

[10. 20. 30.]


In [27]:
#task is to find out what happens if small number is added to 
#large number and then the large number is substracted from the sum

x = 1e9
y = 1e-6


for i in range(0,int(1e6)):
    x= x+y

z= x-1e9

print(z)   

#as we see the result is smaller than 1.0, so where did we loose some numbers?

0.95367431640625


In [ ]:
#useful to plot images

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread(final_path_image)
imgplot = plt.imshow(img)
plt.show()

In [1]:
#generate random ints
from numpy import random

r = random.randint(0,6) #Return random integers from low (inclusive) to high (exclusive).
print (r)

2


In [ ]:
import imageio

image_data = (imageio.imread(final_path_image).astype(float)) #useful for reading in x,y pixel intensities 2D-greyscale-images

In [ ]:
#extending to full relative path from the origin
def extend_filename(origin_path):
    cur_folders = os.listdir(origin_path)
    
    #extensionroutine
    for folder in cur_folders:
        cur_folders  = os.path.join(origin_path,folder)
        #print(cur_folders)
    
    return cur_folders

path_large='./notMNIST_large/' # train dataset
path_small='./notMNIST_small/'# test dataset

#for this tutorial the folder names need to include full relative path, so lets do it
train_folders = extend_filename(path_large)
test_folders = extend_filename(path_small)

In [ ]:
'''Saving python data files as character stream'''

import pickle

a = ['test value','test value 2','test value 3']


file_Name = "testfile"
# open the file for writing
fileObject = open(file_Name,'wb') 

# this writes the object a to the
# file named 'testfile'
pickle.dump(a,fileObject)   

# here we close the fileObject
fileObject.close()
# we open the file for reading
fileObject = open(file_Name,'rb')  #file NEEDS to be read in BINARY mode!
# load the object from the file into var b
b = pickle.load(fileObject)  


In [2]:
'''working with empty helper array'''
import numpy as np

empty_helper= np.array([])
value = 40

empty_helper = np.append (empty_helper, value)
empty_helper = np.append (empty_helper, value)



print (empty_helper)

[40. 40.]


In [11]:
a = np.zeros((1,2,2))
b = np.ones((1,2,2))


c = np.concatenate((a, b), axis=0)


print(c.shape)

print(c[1,:,:])

(2, 2, 2)
[[1. 1.]
 [1. 1.]]


In [9]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (arr)

delarr = np.delete(arr, 0, 0);

print (delarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
np.correlate([0], [0])

array([0])