In [13]:
'''Trick Box'''

'Trick Box'

In [11]:
#numpy evenly spaced array return

import numpy as np

x = np.arange(1,3+1,1) # Return evenly spaced values within a given interval.

scores = np.array([1.0, 2.0, 3.0])
print (scores*10)

[10. 20. 30.]


In [ ]:
#plot images directly

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread(final_path_image)
imgplot = plt.imshow(img)
plt.show()

In [1]:
#generate random integer
from numpy import random

r = random.randint(0,6) #Return random integers from low (inclusive) to high (exclusive).
print (r)

2


In [ ]:
#readin image

import imageio

image_data = (imageio.imread(final_path_image).astype(float)) #useful for reading in x,y pixel intensities 2D-greyscale-images

In [ ]:
#extending to full relative path from the origin
def extend_filename(origin_path, cur_folders):
'''    
joins folder list to some root path origin_path
'''    
    #extensionroutine
    for folder in cur_folders:
        cur_folders  = os.path.join(origin_path,folder)
        #print(cur_folders)
    
    return joined_folders

path_large='./notMNIST_large/' # train dataset
path_small='./notMNIST_small/'# test dataset

#for this tutorial the folder names need to include full relative path, so lets do it
train_folders = extend_filename(path_large, list_of_folder)
test_folders = extend_filename(path_small, list_of_folder)

In [ ]:
'''Saving python data files as character stream into Pickle file'''

import pickle

a = ['test value','test value 2','test value 3']


file_Name = "testfile"
# open the file for writing
fileObject = open(file_Name,'wb') 

# this writes the object a to the
# file named 'testfile'
pickle.dump(a,fileObject)   

# here we close the fileObject
fileObject.close()
# we open the file for reading
fileObject = open(file_Name,'rb')  #file NEEDS to be read in BINARY mode!
# load the object from the file into var b
b = pickle.load(fileObject)  


In [ ]:
'''to store pickle in different destination'''
def maybe_pickle(data_folders, dest_folder, min_num_images_per_class, force=False):
  dataset_names = []
  for folder in data_folders:
    
    set_filename = folder + '.pickle'        
    dest_file = os.path.join(dest_folder,set_filename)
    dataset_names.append(dest_file)
    
    if os.path.exists(dest_file) and not force:
      # You may override by setting force=True.
      print('%s already present - Skipping pickling.' % set_filename)
    else:
      print('Pickling %s.' % set_filename)
      dataset = load_letter(folder, min_num_images_per_class)
      try:
        with open(dest_file, 'wb') as f:
          pickle.dump(dataset, f, pickle.HIGHEST_PROTOCOL)
      except Exception as e:
        print('Unable to save data to', dest_file, ':', e)
  
  return dataset_names

In [2]:
'''working with empty helper array
1. create empty np array
2. append some vlues
'''
import numpy as np

empty_helper= np.array([])
value = 40

empty_helper = np.append (empty_helper, value)
empty_helper = np.append (empty_helper, value)



print (empty_helper)

[40. 40.]


In [16]:
import numpy as np

a = np.zeros((1,2,2))
b = np.ones((1,2,2))


c = np.concatenate((a, b), axis=0)
# [axis 0, axis 1, axis2]

print (a[0,:,:])
print (b[0,:,:])

print(c[0,:,:])

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [9]:
#delete array elements

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (arr)

delarr = np.delete(arr, 0, 0);

print (delarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
np.correlate([0], [0])

array([0])

In [ ]:
'''plotting subplots'''

'''

plt.figure(1)
plt.subplot(211)
plt.imshow(train_dataset_100[25,:,:])

plt.subplot(212)
plt.imshow(cv_dataset_100[66,:,:])
plt.show()  

a = train_dataset_100[25,:,:].ravel();
b = cv_dataset_100[67,:,:].ravel();

dist = np.linalg.norm(a-b)

print(dist)

'''